language: ruby
sudo: false

rvm:
  - 2.3.0
  - 2.2
  - 2.1.2
  - 2.0.0
  - ruby-head
  - jruby-9.1.2.0

env:
  - RSPEC_VERSION=master
  - RSPEC_VERSION='~> 3.0'

bundler_args: "--retry=3 --jobs=3"

script: "bundle exec rake ci --trace"

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.2.0
